"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {Header} from "../../components/site-shell";
import {AdminOrdersManager} from "../../components/admin-orders-manager";
import {api,ApiError} from "../../lib/api";
import {statusLabel} from "../../lib/status-labels";

type Tab="overview"|"users"|"sellers"|"products"|"categories"|"orders"|"finance";
type Page<T>={data:T[];pagination:{page:number;pages:number;total:number}};
type User={id:string;email:string;firstName:string;lastName:string;createdAt:string;suspendedAt:string|null;roles:{role:string}[]};
type Seller={id:string;businessName:string;status:string;applicationAddress?:string|null;activityType?:string|null;additionalInfo?:string|null;rejectionReason?:string|null;appliedAt?:string;user:{email:string;firstName?:string;lastName?:string;phone?:string|null;createdAt:string};store:{name:string;description?:string|null;city?:string|null}|null;_count?:{products:number;sellerOrders:number}};
type Product={id:string;nameHe:string;sku:string;priceAgorot?:number;status:string;createdAt:string;category?:{id:string;nameHe:string};seller:{businessName:string;store:{name:string}|null};variants?:{inventory:{quantity:number}|null}[]};
type Category={id:string;slug:string;nameHe:string;active:boolean;_count:{products:number;children:number}};
type Order={id:string;orderNumber:string;totalAgorot:number;status:string;createdAt:string;user?:{email:string;firstName:string;lastName:string}};
type Stats={totalUsers:number;totalCustomers:number;totalSellers:number;pendingSellers:number;activeStores:number;totalProducts:number;pendingProducts:number;totalOrders:number;pendingPaymentOrders:number;completedOrders:number;totalRevenueAgorot:number;commissionRevenueAgorot:number;sellerNetAgorot:number;refundsAgorot:number;recentOrders:Order[];recentSellers:Seller[];reviewProducts:Product[]};

const tabs:[Tab,string][]=[["overview","סקירה"],["users","משתמשים"],["sellers","מוכרים"],["products","מוצרים"],["categories","קטגוריות"],["orders","הזמנות"],["finance","כספים"]];
const money=(value=0)=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS"}).format(value/100);
const dateTime=(value:string)=>new Intl.DateTimeFormat("he-IL",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jerusalem"}).format(new Date(value));
const options={users:["CUSTOMER","SELLER","ADMIN","SUPER_ADMIN"],sellers:["PENDING","UNDER_REVIEW","APPROVED","REJECTED","SUSPENDED"],products:["DRAFT","PENDING_APPROVAL","ACTIVE","REJECTED","ARCHIVED"]} as const;

export default function AdminPage(){
 const router=useRouter();
 const requestVersion=useRef(0);
 const[tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<unknown>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[toast,setToast]=useState(""),[busy,setBusy]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState(""),[page,setPage]=useState(1);
 const token=()=>localStorage.getItem("shuk-token")??"";
 useEffect(()=>{const sync=()=>setTab(new URLSearchParams(location.search).get("ordersView")==="1"?"orders":"overview");sync();addEventListener("popstate",sync);return()=>removeEventListener("popstate",sync)},[]);
 const load=useCallback(async()=>{const version=++requestVersion.current;if(tab==="orders"){setLoading(false);return}const accessToken=token();if(!accessToken){router.replace("/login");return}setLoading(true);setError("");try{let path=tab==="overview"||tab==="finance"?"/admin/dashboard":`/admin/${tab}`;if(!["overview","finance","categories"].includes(tab)){const query=new URLSearchParams({page:String(page)});if(search)query.set("search",search);if(filter)query.set(tab==="users"?"role":"status",filter);path+=`?${query}`}else if(tab==="categories"&&search)path+=`?search=${encodeURIComponent(search)}`;const result=await api.authGet(path,accessToken);if(version===requestVersion.current)setData(result)}catch(cause){if(version!==requestVersion.current)return;if(cause instanceof ApiError&&cause.status===401){router.replace("/login");return}if(cause instanceof ApiError&&cause.status===403){router.replace("/account");return}setError(cause instanceof Error?cause.message:"טעינת הנתונים נכשלה")}finally{if(version===requestVersion.current)setLoading(false)}},[tab,page,search,filter,router]);
 useEffect(()=>{void load()},[load]);
 function selectTab(next:Tab){requestVersion.current++;setLoading(next!=="orders");setTab(next);setPage(1);setSearch("");setFilter("");setData(null);setError("")}
 async function change(kind:"sellers"|"products",id:string,status:string){if(["REJECTED","SUSPENDED","ARCHIVED"].includes(status)&&!confirm("האם לבצע את הפעולה?"))return;const rejectionReason=kind==="sellers"&&status==="REJECTED"?prompt("סיבת הדחייה — הסיבה תוצג למגיש הבקשה"):undefined;if(kind==="sellers"&&status==="REJECTED"&&!rejectionReason)return;setBusy(id);setError("");try{await api.patch(`/admin/${kind}/${id}/status`,{status,rejectionReason},token());setToast(status==="APPROVED"?"הבקשה אושרה בהצלחה":"הסטטוס עודכן בהצלחה");await load()}catch(cause){setError(cause instanceof Error?cause.message:"עדכון הסטטוס נכשל")}finally{setBusy("");setTimeout(()=>setToast(""),2500)}}
 async function addCategory(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));setBusy("new");try{await api.post("/admin/categories",{nameHe:values.nameHe,slug:values.slug,position:Number(values.position||0)},token());form.reset();setToast("הקטגוריה נוספה");await load()}catch(cause){setError(cause instanceof Error?cause.message:"הוספת הקטגוריה נכשלה")}finally{setBusy("")}}
 async function editCategory(category:Category){const nameHe=prompt("שם הקטגוריה",category.nameHe),slug=nameHe&&prompt("Slug",category.slug);if(!nameHe||!slug)return;setBusy(category.id);try{await api.patch(`/admin/categories/${category.id}`,{nameHe,slug},token());setToast("הקטגוריה עודכנה");await load()}catch(cause){setError(cause instanceof Error?cause.message:"העדכון נכשל")}finally{setBusy("")}}
 async function deleteCategory(category:Category){if(!confirm(`למחוק את ${category.nameHe}?`))return;setBusy(category.id);try{await api.delete(`/admin/categories/${category.id}`,token());setToast("הקטגוריה נמחקה");await load()}catch(cause){setError(cause instanceof Error?cause.message:"המחיקה נכשלה")}finally{setBusy("")}}
 const stats=data as Stats,paged=data as Page<User|Seller|Product>,categories=(data??[])as Category[];
 return <main dir="rtl"><Header/><section className="wrap adminDashboard"><div className="sellerSectionHead"><div><label>ניהול Marketplace</label><h1>לוח ניהול</h1><p>נתונים, בקשות ופעולות מערכת במקום אחד</p></div></div><nav className="adminTabs" aria-label="חלקי לוח הניהול">{tabs.map(([value,label])=><button key={value} className={tab===value?"active":""} aria-current={tab===value?"page":undefined} onClick={()=>selectTab(value)}>{label}</button>)}</nav>{toast&&<div className="adminToast" role="status">✓ {toast}</div>}{error&&<div className="sellerAlert" role="alert"><span>{error}</span><button onClick={()=>void load()}>נסו שוב</button></div>}
 {tab==="orders"?<AdminOrdersManager active token={token()} setError={setError}/>:loading||data===null?<div className="sellerLoading"><span/><p>טוענים נתונים…</p></div>:<>
      {(tab==="overview"||tab==="finance")&&stats&&<Overview stats={stats} finance={tab==="finance"}/>}
 {!["overview","finance"].includes(tab)&&<Panel><div className="adminFilters"><input aria-label="חיפוש" value={search} onChange={event=>setSearch(event.target.value)} placeholder="חיפוש…"/>{tab!=="categories"&&<select aria-label="סינון לפי סטטוס" value={filter} onChange={event=>setFilter(event.target.value)}><option value="">הכול</option>{options[tab as keyof typeof options]?.map(value=><option key={value}>{value}</option>)}</select>}</div>
 {tab==="users"&&<Table headings={["שם","אימייל","תפקיד","תאריך הצטרפות","סטטוס"]}>{(paged.data as User[]).map(user=><tr key={user.id}><td>{user.firstName} {user.lastName}</td><td dir="ltr">{user.email}</td><td>{user.roles.map(role=>statusLabel(role.role)).join(", ")}</td><td>{dateTime(user.createdAt)}</td><td><Badge value={user.suspendedAt?"SUSPENDED":"ACTIVE"}/></td></tr>)}</Table>}
 {tab==="sellers"&&<Table headings={["מגיש הבקשה","חנות ופרטים","פעילות","סטטוס","מוצרים","הזמנות","הוגש","פעולות"]}>{(paged.data as Seller[]).map(seller=><tr key={seller.id}><td><b>{seller.user.firstName} {seller.user.lastName}</b><small dir="ltr">{seller.user.email}</small><div className="rowActions"><a href={`mailto:${seller.user.email}`}>שליחת אימייל</a>{seller.user.phone&&<a dir="ltr" href={`tel:${seller.user.phone}`}>{seller.user.phone}</a>}</div></td><td><b>{seller.store?.name??seller.businessName}</b><small>{seller.store?.city??"לא צוין"} · {seller.applicationAddress??"ללא כתובת"}</small><small>{seller.store?.description}</small></td><td>{seller.activityType??"לא צוין"}<small>{seller.additionalInfo}</small></td><td><Badge value={seller.status}/>{seller.rejectionReason&&<small>{seller.rejectionReason}</small>}</td><td>{seller._count?.products??0}</td><td>{seller._count?.sellerOrders??0}</td><td>{dateTime(seller.appliedAt??seller.user.createdAt)}</td><td><Actions disabled={busy===seller.id} values={[["אישור","APPROVED"],["דחייה","REJECTED"],["השעיה","SUSPENDED"]]} run={value=>void change("sellers",seller.id,value)}/></td></tr>)}</Table>}
 {tab==="products"&&<Table headings={["מוצר","מוכר","קטגוריה","SKU","מחיר","מלאי","סטטוס","תאריך","פעולות"]}>{(paged.data as Product[]).map(product=><tr key={product.id}><td>{product.nameHe}</td><td>{product.seller.businessName}<small>{product.seller.store?.name}</small></td><td>{product.category?.nameHe??"—"}</td><td dir="ltr">{product.sku}</td><td>{money(product.priceAgorot)}</td><td>{product.variants?.reduce((sum,item)=>sum+(item.inventory?.quantity??0),0)??0}</td><td><Badge value={product.status}/></td><td>{dateTime(product.createdAt)}</td><td><Actions disabled={busy===product.id} values={[["הפעלה","ACTIVE"],["דחייה","REJECTED"],["ארכוב","ARCHIVED"]]} run={value=>void change("products",product.id,value)}/></td></tr>)}</Table>}
 {tab==="categories"&&<><form className="adminCategoryForm" onSubmit={addCategory}><label><span>שם בעברית</span><input name="nameHe" required/></label><label><span>Slug</span><input name="slug" dir="ltr" pattern="[a-z0-9-]+" required/></label><label><span>מיקום</span><input name="position" type="number" min="0" defaultValue="0"/></label><button className="primary" disabled={busy==="new"}>הוספה</button></form><Table headings={["שם","Slug","מוצרים","קטגוריות משנה","פעילה","פעולות"]}>{categories.map(category=><tr key={category.id}><td>{category.nameHe}</td><td dir="ltr">{category.slug}</td><td>{category._count.products}</td><td>{category._count.children}</td><td>{category.active?"כן":"לא"}</td><td><Actions disabled={busy===category.id} values={[["עריכה","edit"],["מחיקה","delete"]]} run={value=>value==="edit"?void editCategory(category):void deleteCategory(category)}/></td></tr>)}</Table></>}
 {tab!=="categories"&&paged?.pagination&&<div className="pagination"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>הקודם</button><span>עמוד {page} מתוך {paged.pagination.pages||1}</span><button disabled={page>=paged.pagination.pages} onClick={()=>setPage(value=>value+1)}>הבא</button></div>}</Panel>}</>}
 </section></main>
}

function Overview({stats,finance}:{stats:Stats;finance:boolean}){const cards=finance?[["מכירות",money(stats.totalRevenueAgorot)],["עמלות",money(stats.commissionRevenueAgorot)],["נטו למוכרים",money(stats.sellerNetAgorot)],["החזרים",money(stats.refundsAgorot)]]:[["משתמשים",stats.totalUsers],["לקוחות",stats.totalCustomers],["מוכרים",stats.totalSellers],["בקשות ממתינות",stats.pendingSellers],["חנויות פעילות",stats.activeStores],["מוצרים",stats.totalProducts],["מוצרים לבדיקה",stats.pendingProducts],["הזמנות",stats.totalOrders],["שווי הזמנות",money(stats.totalRevenueAgorot)],["עמלות",money(stats.commissionRevenueAgorot)],["ממתינות לתשלום",stats.pendingPaymentOrders],["הושלמו",stats.completedOrders]];return <><div className="adminStats">{cards.map(([label,value])=><article key={label}><small>{label}</small><b>{value}</b></article>)}</div>{!finance&&<div className="adminOverviewGrid"><Panel title="הזמנות אחרונות">{stats.recentOrders.length?stats.recentOrders.map(order=><div className="adminRecent" key={order.id}><b dir="ltr">{order.orderNumber}</b><Badge value={order.status}/><span>{money(order.totalAgorot)}</span><small>{dateTime(order.createdAt)}</small></div>):<Empty/>}</Panel><Panel title="מוכרים חדשים">{stats.recentSellers.length?stats.recentSellers.map(seller=><div className="adminRecent" key={seller.id}><b>{seller.businessName}</b><span>{seller.store?.name??"—"}</span><Badge value={seller.status}/><small>{dateTime(seller.user.createdAt)}</small></div>):<Empty/>}</Panel><Panel title="מוצרים לבדיקה">{stats.reviewProducts.length?stats.reviewProducts.map(product=><div className="adminRecent" key={product.id}><b>{product.nameHe}</b><span>{product.seller.businessName}</span><Badge value={product.status}/><small>{dateTime(product.createdAt)}</small></div>):<Empty/>}</Panel></div>}</>}
function Badge({value}:{value:string}){return <span className={`statusBadge status-${value.toLowerCase()}`}>{statusLabel(value)}</span>}
function Actions({values,run,disabled}:{values:[string,string][];run:(value:string)=>void;disabled:boolean}){return <div className="rowActions">{values.map(([label,value])=><button type="button" disabled={disabled} key={value} onClick={()=>run(value)}>{disabled?"מעדכנים…":label}</button>)}</div>}
function Table({headings,children}:{headings:string[];children:React.ReactNode}){return <div className="sellerTableWrap"><table className="sellerTable adminTable"><thead><tr>{headings.map(heading=><th key={heading}>{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Panel({title,children}:{title?:string;children:React.ReactNode}){return <section className="sellerPanel">{title&&<h2>{title}</h2>}{children}</section>}
function Empty(){return <div className="adminEmpty">אין נתונים להצגה</div>}
