"use client";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {Suspense,useCallback,useEffect,useState} from "react";
import {Footer,Header} from "../../components/site-shell";
import {api} from "../../lib/api";
type Address={fullName?:string;phone?:string;city?:string;street?:string;houseNumber?:string;apartment?:string;postalCode?:string};
type PaymentOrder={id:string;orderNumber:string;state:"PENDING_PAYMENT"|"PROCESSING"|"PAID"|"FAILED"|"CANCELLED"|"UNAVAILABLE";orderStatus:string;paymentStatus:string|null;currency:string;subtotalAgorot:number;shippingAgorot:number;totalAgorot:number;shippingAddress:Address;items:{id:string;productName:string;sku:string;variantName:string|null;quantity:number;unitPriceAgorot:number;discountAgorot:number;sellerName:string}[]};
const money=(value:number)=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS"}).format(value/100);
function PaymentContent(){
 const params=useSearchParams(),orderId=params.get("orderId"),[order,setOrder]=useState<PaymentOrder|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!orderId){setLoading(false);setError("לא נבחרה הזמנה לתשלום");return}const token=localStorage.getItem("shuk-token");if(!token){setLoading(false);setError("יש להתחבר כדי לצפות בתשלום");return}setLoading(true);setError("");try{setOrder(await api.authGet<PaymentOrder>(`/payments/orders/${encodeURIComponent(orderId)}`,token))}catch(cause){setOrder(null);setError((cause as Error).message)}finally{setLoading(false)}},[orderId]);
 useEffect(()=>{void load()},[load]);
 if(loading)return <div className="paymentPageState"><div className="paymentPageSkeleton"><span/><span/><span/></div><p>טוענים את פרטי ההזמנה…</p></div>;
 if(error||!order)return <div className="paymentPageState"><span className="stateIcon">!</span><h1>לא ניתן לפתוח את התשלום</h1><p>{error}</p><div><button className="primary" onClick={()=>void load()}>נסו שוב</button><Link className="ghost" href="/checkout">חזרה לקופה</Link></div></div>;
 if(order.state==="PAID")return <div className="paymentPageState successState"><span className="stateIcon">✓</span><h1>ההזמנה כבר שולמה</h1><p>לא ניתן לשלם שוב עבור הזמנה זו.</p><b dir="ltr">{order.orderNumber}</b><Link className="primary" href="/account">להזמנות שלי</Link></div>;
 if(order.state==="PROCESSING")return <div className="paymentPageState"><span className="stateIcon">…</span><h1>התשלום נמצא בעיבוד</h1><p>כבר קיים ניסיון תשלום להזמנה זו, ולכן לא ניתן להתחיל ניסיון נוסף.</p><button className="primary" onClick={()=>void load()}>בדיקת מצב מחדש</button><Link className="ghost" href="/account">להזמנות שלי</Link></div>;
 if(order.state==="FAILED")return <div className="paymentPageState"><span className="stateIcon">!</span><h1>ניסיון התשלום נכשל</h1><p>לא בוצע חיוב. ספק התשלום עדיין אינו מחובר בסביבת הבדיקה.</p><button className="primary" onClick={()=>void load()}>רענון מצב ההזמנה</button><Link className="ghost" href="/account">להזמנות שלי</Link></div>;
 if(order.state!=="PENDING_PAYMENT")return <div className="paymentPageState"><span className="stateIcon">×</span><h1>ההזמנה אינה זמינה לתשלום</h1><p>מצב ההזמנה הנוכחי אינו מאפשר פתיחת תשלום.</p><Link className="primary" href="/account">להזמנות שלי</Link></div>;
 const address=order.shippingAddress;
 return <div className="paymentLayout"><section className="paymentMain"><div className="paymentHeading"><label>תשלום מאובטח</label><h1>בחירת אמצעי תשלום</h1><p>ספק תשלום טרם חובר. לא יתבצע חיוב בסביבת הבדיקה.</p></div><div className="paymentWarning" role="status">מצב הכנה בלבד — פרטי כרטיס אינם נאספים או נשלחים.</div><div className="paymentMethods"><label className="method active"><input type="radio" checked readOnly/><span>💳</span><div><b>כרטיס אשראי או חיוב</b><small>יופעל לאחר חיבור ספק התשלום</small></div><em>בקרוב</em></label><label className="method disabled"><input type="radio" disabled/><span aria-hidden="true">●</span><div><b>Apple Pay</b><small>בקרוב</small></div></label><label className="method disabled"><input type="radio" disabled/><span aria-hidden="true">G</span><div><b>Google Pay</b><small>בקרוב</small></div></label></div><div className="futureCardForm" aria-disabled="true"><label>מספר כרטיס<input disabled placeholder="•••• •••• •••• ••••"/></label><div><label>תוקף<input disabled placeholder="MM/YY"/></label><label>CVV<input disabled placeholder="•••"/></label></div><label>שם בעל הכרטיס<input disabled placeholder="שם מלא"/></label></div><button className="primary paymentDisabled" disabled>תשלום {money(order.totalAgorot)} — לא זמין כעת</button><small className="providerNote">לא נשמרים פרטי תשלום. לאחר חיבור ספק עתידי, הצלחה תאושר רק באמצעות Webhook מאומת.</small></section><aside className="paymentSummary"><div className="paymentOrderNumber"><small>הזמנה</small><b dir="ltr">{order.orderNumber}</b></div><h2>סיכום ההזמנה</h2><div className="paymentItems">{order.items.map(item=><article key={item.id}><div><b>{item.productName}</b><small>{item.sellerName} · {item.variantName??item.sku}</small></div><span>{item.quantity} × {money(item.unitPriceAgorot)}</span></article>)}</div><div className="paymentTotals"><p>סכום ביניים <b>{money(order.subtotalAgorot)}</b></p><p>משלוח <b>{order.shippingAgorot?money(order.shippingAgorot):"חינם"}</b></p><hr/><p className="total">סה״כ <b>{money(order.totalAgorot)}</b></p></div><div className="paymentAddress"><small>משלוח אל</small><b>{address.fullName}</b><span>{address.street} {address.houseNumber}{address.apartment?`, דירה ${address.apartment}`:""}, {address.city}</span>{address.phone&&<span dir="ltr">{address.phone}</span>}</div><Link className="backCheckout" href="/checkout">← חזרה לקופה</Link></aside></div>
}
export default function PaymentPage(){return <main dir="rtl"><Header/><section className="wrap paymentPage"><Suspense fallback={<div className="customerLoading"><span/></div>}><PaymentContent/></Suspense></section><Footer/></main>}
