import { Body, Controller, Delete, Get, NotFoundException, Param, ParseUUIDPipe, Patch, Post, UseGuards } from '@nestjs/common';
import { IsBoolean, IsOptional, IsString, Matches, MaxLength, MinLength } from 'class-validator';
import { AuthUser, CurrentUser, JwtAuthGuard } from './auth';
import { PrismaService } from './prisma';
class AddressDto {@IsString() @MinLength(2) @MaxLength(100) fullName!:string;@IsString() @Matches(/^[0-9+()\-\s]{7,20}$/) phone!:string;@IsString() @MinLength(2) @MaxLength(80) city!:string;@IsString() @MinLength(2) @MaxLength(120) street!:string;@IsString() @MinLength(1) @MaxLength(20) houseNumber!:string;@IsOptional() @IsString() @MaxLength(20) apartment?:string;@IsOptional() @IsString() @MaxLength(20) postalCode?:string;@IsOptional() @IsString() @MaxLength(300) notes?:string;@IsOptional() @IsBoolean() isDefault?:boolean;}
class UpdateAddressDto {@IsOptional() @IsString() @MinLength(2) @MaxLength(100) fullName?:string;@IsOptional() @IsString() @Matches(/^[0-9+()\-\s]{7,20}$/) phone?:string;@IsOptional() @IsString() @MinLength(2) @MaxLength(80) city?:string;@IsOptional() @IsString() @MinLength(2) @MaxLength(120) street?:string;@IsOptional() @IsString() @MinLength(1) @MaxLength(20) houseNumber?:string;@IsOptional() @IsString() @MaxLength(20) apartment?:string;@IsOptional() @IsString() @MaxLength(20) postalCode?:string;@IsOptional() @IsString() @MaxLength(300) notes?:string;@IsOptional() @IsBoolean() isDefault?:boolean;}
@UseGuards(JwtAuthGuard) @Controller('addresses')
export class AddressesController {constructor(private readonly db:PrismaService){}
@Get() list(@CurrentUser() user:AuthUser){return this.db.address.findMany({where:{userId:user.sub},orderBy:[{isDefault:'desc'},{createdAt:'desc'}]});}
@Post() async create(@CurrentUser() user:AuthUser,@Body() dto:AddressDto){return this.db.$transaction(async tx=>{const first=await tx.address.count({where:{userId:user.sub}})===0;const makeDefault=first||dto.isDefault===true;if(makeDefault)await tx.address.updateMany({where:{userId:user.sub},data:{isDefault:false}});return tx.address.create({data:{userId:user.sub,fullName:dto.fullName.trim(),phone:dto.phone.trim(),city:dto.city.trim(),street:dto.street.trim(),building:dto.houseNumber.trim(),apartment:dto.apartment?.trim()||null,postalCode:dto.postalCode?.trim()||null,instructions:dto.notes?.trim()||null,isDefault:makeDefault}});});}
@Patch(':id') async update(@CurrentUser() user:AuthUser,@Param('id',ParseUUIDPipe) id:string,@Body() dto:UpdateAddressDto){const found=await this.db.address.findFirst({where:{id,userId:user.sub}});if(!found)throw new NotFoundException('הכתובת לא נמצאה');return this.db.$transaction(async tx=>{if(dto.isDefault===true)await tx.address.updateMany({where:{userId:user.sub},data:{isDefault:false}});return tx.address.update({where:{id},data:{fullName:dto.fullName?.trim(),phone:dto.phone?.trim(),city:dto.city?.trim(),street:dto.street?.trim(),building:dto.houseNumber?.trim(),apartment:dto.apartment?.trim()||null,postalCode:dto.postalCode?.trim()||null,instructions:dto.notes?.trim()||null,isDefault:dto.isDefault===true?true:undefined}});});}
@Patch(':id/default') async setDefault(@CurrentUser() user:AuthUser,@Param('id',ParseUUIDPipe) id:string){const found=await this.db.address.findFirst({where:{id,userId:user.sub}});if(!found)throw new NotFoundException('הכתובת לא נמצאה');return this.db.$transaction(async tx=>{await tx.address.updateMany({where:{userId:user.sub},data:{isDefault:false}});return tx.address.update({where:{id},data:{isDefault:true}});});}
@Delete(':id') async remove(@CurrentUser() user:AuthUser,@Param('id',ParseUUIDPipe) id:string){const found=await this.db.address.findFirst({where:{id,userId:user.sub}});if(!found)throw new NotFoundException('הכתובת לא נמצאה');await this.db.$transaction(async tx=>{await tx.address.delete({where:{id}});if(found.isDefault){const next=await tx.address.findFirst({where:{userId:user.sub},orderBy:{createdAt:'desc'}});if(next)await tx.address.update({where:{id:next.id},data:{isDefault:true}});}});return{message:'הכתובת נמחקה'};}}
