import { BadRequestException, Body, ConflictException, Controller, Delete, ForbiddenException, Get, Injectable, NotFoundException, Param, ParseUUIDPipe, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { OrderStatus, PaymentStatus, ProductStatus, Role, SellerStatus } from '@prisma/client';
import { IsBoolean, IsEnum, IsInt, IsOptional, IsString, IsUUID, Max, MaxLength, Min, MinLength } from 'class-validator';
import { AuthUser, CurrentUser, JwtAuthGuard, RateLimitService, RequireRoles } from './auth';
import { PrismaService } from './prisma';

class ProductDto {
  @IsString() @MinLength(2) @MaxLength(200) nameHe!: string; @IsString() @MinLength(2) @MaxLength(5000) descriptionHe!: string;
  @IsUUID() categoryId!: string; @IsString() @MinLength(2) @MaxLength(100) sku!: string; @IsInt() @Min(1) @Max(100000000) priceAgorot!: number;
  @IsOptional() @IsInt() @Min(0) @Max(100000000) compareAtAgorot?: number; @IsOptional() @IsBoolean() supportsFastDelivery?: boolean;
  @IsInt() @Min(0) @Max(100000) quantity!: number;
}
class StockDto { @IsInt() @Min(0) @Max(100000) quantity!: number; }
class UpdateProductDto { @IsOptional() @IsString() @MinLength(2) @MaxLength(200) nameHe?: string; @IsOptional() @IsString() @MinLength(2) @MaxLength(5000) descriptionHe?: string; @IsOptional() @IsInt() @Min(1) @Max(100000000) priceAgorot?: number; @IsOptional() @IsInt() @Min(0) @Max(100000000) compareAtAgorot?: number; @IsOptional() @IsBoolean() supportsFastDelivery?: boolean; }
class SellerApplicationDto {
  @IsString() @MinLength(2) @MaxLength(120) storeName!: string; @IsString() @MinLength(10) @MaxLength(2000) storeDescription!: string;
  @IsString() @MinLength(7) @MaxLength(30) phone!: string; @IsString() @MinLength(2) @MaxLength(80) city!: string;
  @IsString() @MinLength(3) @MaxLength(200) address!: string; @IsString() @MinLength(2) @MaxLength(120) activityType!: string;
  @IsOptional() @IsString() @MaxLength(2000) additionalInfo?: string;
}

@Injectable()
class SellerService {
  constructor(private readonly db: PrismaService) {}
  private async seller(userId: string) { const seller = await this.db.sellerProfile.findUnique({ where: { userId } }); if (!seller) throw new NotFoundException('חשבון מוכר לא נמצא'); if(seller.status!==SellerStatus.APPROVED)throw new ForbiddenException('חשבון המוכר עדיין אינו מאושר'); return seller; }
  async dashboard(userId: string) {
    const seller = await this.seller(userId);
    const [orders, products, pending, totals] = await this.db.$transaction([this.db.sellerOrder.count({ where: { sellerId: seller.id } }), this.db.product.count({ where: { sellerId: seller.id, deletedAt: null } }), this.db.sellerOrder.count({ where: { sellerId: seller.id, status: { in: ['PAID', 'PROCESSING', 'READY_TO_SHIP'] } } }), this.db.sellerOrder.aggregate({ where: { sellerId: seller.id, status: { notIn: ['CANCELLED', 'REFUNDED'] } }, _sum: { subtotalAgorot: true, netAgorot: true } })]);
    return { orders, products, pendingOrders: pending, salesAgorot: totals._sum.subtotalAgorot ?? 0, revenueAgorot: totals._sum.netAgorot ?? 0, currency: 'ILS' };
  }
  async products(userId: string) { const seller = await this.seller(userId); return this.db.product.findMany({ where: { sellerId: seller.id, deletedAt: null }, include: { variants: { include: { inventory: true } }, images:{orderBy:{position:'asc'}}, category: true }, orderBy: { createdAt: 'desc' } }); }
  async create(userId: string, dto: ProductDto) { const seller = await this.seller(userId); const sku=dto.sku.trim();if(await this.db.product.findUnique({where:{sellerId_sku:{sellerId:seller.id,sku}}}))throw new ConflictException('SKU כבר קיים בחנות');if(!await this.db.category.findUnique({where:{id:dto.categoryId},select:{id:true}}))throw new BadRequestException('קטגוריה לא תקינה');const slug = `${sku.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${Date.now()}`;try{return await this.db.product.create({ data: { sellerId: seller.id, categoryId: dto.categoryId, slug, sku, nameHe: dto.nameHe.trim(), descriptionHe: dto.descriptionHe.trim(), priceAgorot: dto.priceAgorot, compareAtAgorot: dto.compareAtAgorot, supportsFastDelivery: dto.supportsFastDelivery, status: ProductStatus.ACTIVE, variants: { create: { sku: `${sku}-${seller.id.slice(0,8)}-STD`, name: 'רגיל', inventory: { create: { quantity: dto.quantity } } } } }, include: { variants: { include: { inventory: true } } } });}catch(error){if(typeof error==='object'&&error!==null&&'code'in error&&(error as {code?:string}).code==='P2002')throw new ConflictException('SKU כבר קיים בחנות');throw error;} }
  async update(userId: string, productId: string, dto: UpdateProductDto) { const seller = await this.seller(userId); const found = await this.db.product.findFirst({ where: { id: productId, sellerId: seller.id, deletedAt: null } }); if (!found) throw new NotFoundException(); return this.db.product.update({ where: { id: found.id }, data: dto }); }
  async stock(userId: string, variantId: string, dto: StockDto) { const seller = await this.seller(userId); const variant = await this.db.productVariant.findFirst({ where: { id: variantId, product: { sellerId: seller.id } } }); if (!variant) throw new NotFoundException(); return this.db.inventory.update({ where: { variantId }, data: { quantity: dto.quantity, version: { increment: 1 } } }); }
}

@Controller('seller')
export class SellerController {
  constructor(private readonly seller: SellerService, private readonly db: PrismaService,private readonly rateLimit:RateLimitService) {}
  @UseGuards(JwtAuthGuard) @Get('application') application(@CurrentUser() user:AuthUser){return this.db.sellerProfile.findUnique({where:{userId:user.sub},select:{id:true,status:true,activityType:true,applicationAddress:true,additionalInfo:true,rejectionReason:true,appliedAt:true,store:{select:{name:true,description:true,city:true}}}});}
  @UseGuards(JwtAuthGuard) @Post('apply') async apply(@CurrentUser() user:AuthUser,@Body() dto:SellerApplicationDto){
    await this.rateLimit.consume(`seller-application:${user.sub}`,5,60*60*1000);
    const existing=await this.db.sellerProfile.findUnique({where:{userId:user.sub}});if(existing&&(existing.status===SellerStatus.PENDING||existing.status===SellerStatus.UNDER_REVIEW))throw new ConflictException('בקשת פתיחת חנות כבר נמצאת בבדיקה');if(existing?.status===SellerStatus.APPROVED)throw new ConflictException('חשבון המוכר כבר מאושר');
    const slug=`store-${user.sub.slice(0,8)}-${Date.now()}`;return this.db.$transaction(async tx=>{await tx.user.update({where:{id:user.sub},data:{phone:dto.phone}});if(existing){return tx.sellerProfile.update({where:{id:existing.id},data:{businessName:dto.storeName,status:SellerStatus.PENDING,applicationAddress:dto.address,activityType:dto.activityType,additionalInfo:dto.additionalInfo,rejectionReason:null,appliedAt:new Date(),store:{upsert:{create:{slug,name:dto.storeName,description:dto.storeDescription,city:dto.city},update:{name:dto.storeName,description:dto.storeDescription,city:dto.city}}}},include:{store:true}});}return tx.sellerProfile.create({data:{userId:user.sub,businessName:dto.storeName,status:SellerStatus.PENDING,applicationAddress:dto.address,activityType:dto.activityType,additionalInfo:dto.additionalInfo,store:{create:{slug,name:dto.storeName,description:dto.storeDescription,city:dto.city}}},include:{store:true}});});
  }
  @RequireRoles(Role.SELLER, Role.ADMIN, Role.SUPER_ADMIN) @Get('dashboard') dashboard(@CurrentUser() user: AuthUser) { return this.seller.dashboard(user.sub); }
  @RequireRoles(Role.SELLER, Role.ADMIN, Role.SUPER_ADMIN) @Get('products') products(@CurrentUser() user: AuthUser) { return this.seller.products(user.sub); }
  @RequireRoles(Role.SELLER, Role.ADMIN, Role.SUPER_ADMIN) @Post('products') create(@CurrentUser() user: AuthUser, @Body() dto: ProductDto) { return this.seller.create(user.sub, dto); }
  @RequireRoles(Role.SELLER, Role.ADMIN, Role.SUPER_ADMIN) @Patch('products/:id') update(@CurrentUser() user: AuthUser, @Param('id') id: string, @Body() dto: UpdateProductDto) { return this.seller.update(user.sub, id, dto); }
  @RequireRoles(Role.SELLER, Role.ADMIN, Role.SUPER_ADMIN) @Patch('variants/:id/stock') stock(@CurrentUser() user: AuthUser, @Param('id') id: string, @Body() dto: StockDto) { return this.seller.stock(user.sub, id, dto); }
  @RequireRoles(Role.SELLER, Role.ADMIN, Role.SUPER_ADMIN) @Get('orders') async orders(@CurrentUser() user: AuthUser): Promise<unknown> { const seller = await this.db.sellerProfile.findUniqueOrThrow({ where: { userId: user.sub } }); return this.db.sellerOrder.findMany({ where: { sellerId: seller.id }, include: { order: { select:{orderNumber:true,createdAt:true,status:true,shippingAddress:true,payment:{select:{status:true}}} }, items: true }, orderBy: { order: { createdAt: 'desc' } } }); }
}

class AdminSellerStatusDto{@IsEnum(SellerStatus) status!:SellerStatus;@IsOptional() @IsString() @MinLength(2) rejectionReason?:string;}
class AdminProductStatusDto{@IsEnum(ProductStatus) status!:ProductStatus;}
class AdminCategoryDto{@IsString() @MinLength(2) nameHe!:string;@IsString() @MinLength(2) slug!:string;@IsOptional() @IsString() nameAr?:string;@IsOptional() @IsString() nameEn?:string;@IsOptional() @IsUUID() parentId?:string;@IsOptional() @IsBoolean() active?:boolean;@IsOptional() @IsInt() position?:number;}
class AdminUpdateCategoryDto{@IsOptional() @IsString() @MinLength(2) nameHe?:string;@IsOptional() @IsString() @MinLength(2) slug?:string;@IsOptional() @IsString() nameAr?:string;@IsOptional() @IsString() nameEn?:string;@IsOptional() @IsUUID() parentId?:string;@IsOptional() @IsBoolean() active?:boolean;@IsOptional() @IsInt() position?:number;}

@Controller('admin')
export class AdminController {
  constructor(private readonly db: PrismaService,private readonly rateLimit:RateLimitService) {}
  @RequireRoles(Role.ADMIN, Role.SUPER_ADMIN) @Get('dashboard') async dashboard() {
    const [totalUsers,totalCustomers,totalSellers,pendingSellers,activeStores,totalProducts,pendingProducts,totalOrders,pendingPaymentOrders,paidOrders,completedOrders,sales,finance,recentOrders,refunds,recentSellers,reviewProducts] = await this.db.$transaction([
      this.db.user.count(),this.db.user.count({where:{roles:{some:{role:Role.CUSTOMER}}}}),this.db.sellerProfile.count(),this.db.sellerProfile.count({where:{status:{in:[SellerStatus.PENDING,SellerStatus.UNDER_REVIEW]}}}),this.db.store.count({where:{seller:{status:SellerStatus.APPROVED}}}),this.db.product.count({where:{deletedAt:null}}),this.db.product.count({where:{deletedAt:null,status:{in:[ProductStatus.DRAFT,ProductStatus.PENDING_APPROVAL]}}}),this.db.order.count(),this.db.order.count({where:{payment:{is:{status:PaymentStatus.PENDING}}}}),this.db.order.count({where:{status:{in:[OrderStatus.PAID,OrderStatus.PROCESSING,OrderStatus.READY_TO_SHIP,OrderStatus.SHIPPED,OrderStatus.IN_TRANSIT,OrderStatus.DELIVERED]}}}),this.db.order.count({where:{status:OrderStatus.DELIVERED}}),this.db.order.aggregate({where:{status:{notIn:[OrderStatus.CANCELLED,OrderStatus.REFUNDED]}},_sum:{totalAgorot:true}}),this.db.sellerOrder.aggregate({where:{status:{notIn:[OrderStatus.CANCELLED,OrderStatus.REFUNDED]}},_sum:{commissionAgorot:true,netAgorot:true}}),this.db.order.findMany({take:10,orderBy:{createdAt:'desc'},select:{id:true,orderNumber:true,status:true,totalAgorot:true,createdAt:true,user:{select:{email:true,firstName:true,lastName:true}}}}),this.db.ledgerEntry.aggregate({where:{type:'REFUND'},_sum:{amountAgorot:true}}),this.db.sellerProfile.findMany({take:5,orderBy:{user:{createdAt:'desc'}},select:{id:true,businessName:true,status:true,user:{select:{email:true,createdAt:true}},store:{select:{name:true}}}}),this.db.product.findMany({take:5,where:{deletedAt:null,status:{in:[ProductStatus.DRAFT,ProductStatus.PENDING_APPROVAL]}},orderBy:{createdAt:'desc'},select:{id:true,nameHe:true,sku:true,status:true,createdAt:true,seller:{select:{businessName:true,store:{select:{name:true}}}}}})
    ]);
    return {totalUsers,totalCustomers,totalSellers,pendingSellers,activeStores,totalProducts,pendingProducts,totalOrders,pendingPaymentOrders,paidOrders,completedOrders,totalRevenueAgorot:sales._sum.totalAgorot??0,commissionRevenueAgorot:finance._sum.commissionAgorot??0,sellerNetAgorot:finance._sum.netAgorot??0,refundsAgorot:refunds._sum.amountAgorot??0,recentOrders,recentSellers,reviewProducts,currency:'ILS'};
  }

  private page(queryPage?:string,queryLimit?:string){const page=Math.max(1,Number(queryPage)||1);const limit=Math.min(100,Math.max(1,Number(queryLimit)||20));return{page,limit,skip:(page-1)*limit};}

  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Get('users') async users(@Query('search') search='',@Query('role') role='',@Query('page') pageText?:string,@Query('limit') limitText?:string){
    const {page,limit,skip}=this.page(pageText,limitText); if(role&&!Object.values(Role).includes(role as Role))throw new BadRequestException('תפקיד לא תקין');
    const where={...(search?{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}}]}:{}),...(role?{roles:{some:{role:role as Role}}}:{})};
    const [data,total]=await this.db.$transaction([this.db.user.findMany({where,skip,take:limit,orderBy:{createdAt:'desc'},select:{id:true,email:true,firstName:true,lastName:true,createdAt:true,suspendedAt:true,roles:{select:{role:true}}}}),this.db.user.count({where})]);return{data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}};
  }

  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Get('sellers') async sellers(@Query('status') status='',@Query('search') search='',@Query('page') pageText?:string,@Query('limit') limitText?:string){
    const {page,limit,skip}=this.page(pageText,limitText);if(status&&!Object.values(SellerStatus).includes(status as SellerStatus))throw new BadRequestException('סטטוס לא תקין');const where={...(status?{status:status as SellerStatus}:{}),...(search?{OR:[{businessName:{contains:search,mode:'insensitive' as const}},{user:{email:{contains:search,mode:'insensitive' as const}}},{store:{name:{contains:search,mode:'insensitive' as const}}}]}:{})};const [data,total]=await this.db.$transaction([this.db.sellerProfile.findMany({where,skip,take:limit,orderBy:{appliedAt:'desc'},select:{id:true,businessName:true,status:true,applicationAddress:true,activityType:true,additionalInfo:true,rejectionReason:true,appliedAt:true,user:{select:{email:true,firstName:true,lastName:true,phone:true,createdAt:true}},store:{select:{name:true,description:true,city:true}},_count:{select:{products:true,sellerOrders:true}}}}),this.db.sellerProfile.count({where})]);return{data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}};
  }
  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Patch('sellers/:id/status') async sellerStatus(@CurrentUser() admin:AuthUser,@Param('id',ParseUUIDPipe) id:string,@Body() dto:AdminSellerStatusDto){await this.rateLimit.consume(`admin-sensitive:${admin.sub}`,30,60*1000);const found=await this.db.sellerProfile.findUnique({where:{id},select:{id:true,userId:true,status:true}});if(!found)throw new NotFoundException('המוכר לא נמצא');if(found.status===dto.status)throw new ConflictException('סטטוס המוכר כבר עודכן');if(dto.status===SellerStatus.REJECTED&&!dto.rejectionReason)throw new BadRequestException('יש לציין סיבת דחייה');return this.db.$transaction(async tx=>{const claimed=await tx.sellerProfile.updateMany({where:{id,status:found.status},data:{status:dto.status,rejectionReason:dto.status===SellerStatus.REJECTED?dto.rejectionReason:null}});if(claimed.count!==1)throw new ConflictException('סטטוס המוכר השתנה. רעננו ונסו שוב');const updated={id,status:dto.status};if(dto.status===SellerStatus.APPROVED)await tx.userRole.upsert({where:{userId_role:{userId:found.userId,role:Role.SELLER}},create:{userId:found.userId,role:Role.SELLER},update:{}});else if(dto.status===SellerStatus.REJECTED)await tx.userRole.deleteMany({where:{userId:found.userId,role:Role.SELLER}});const action=dto.status===SellerStatus.APPROVED?'ADMIN_SELLER_APPLICATION_APPROVED':dto.status===SellerStatus.REJECTED?'ADMIN_SELLER_APPLICATION_REJECTED':'ADMIN_SELLER_STATUS_CHANGED';await tx.auditLog.create({data:{actorId:admin.sub,action,entityType:'SellerProfile',entityId:id,metadata:{targetUserId:found.userId,previousStatus:found.status,newStatus:dto.status,rejectionReason:dto.rejectionReason}}});return updated;});}

  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Get('products') async products(@Query('status') status='',@Query('sellerId') sellerId='',@Query('categoryId') categoryId='',@Query('search') search='',@Query('page') pageText?:string,@Query('limit') limitText?:string){
    const {page,limit,skip}=this.page(pageText,limitText);if(status&&!Object.values(ProductStatus).includes(status as ProductStatus))throw new BadRequestException('סטטוס לא תקין');const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;if(sellerId&&!uuid.test(sellerId))throw new BadRequestException('מזהה מוכר לא תקין');if(categoryId&&!uuid.test(categoryId))throw new BadRequestException('מזהה קטגוריה לא תקין');const where={deletedAt:null,...(status?{status:status as ProductStatus}:{}),...(sellerId?{sellerId}:{}),...(categoryId?{categoryId}:{}),...(search?{OR:[{nameHe:{contains:search,mode:'insensitive' as const}},{sku:{contains:search,mode:'insensitive' as const}}]}:{})};const [data,total]=await this.db.$transaction([this.db.product.findMany({where,skip,take:limit,orderBy:{createdAt:'desc'},select:{id:true,nameHe:true,sku:true,priceAgorot:true,status:true,createdAt:true,images:{orderBy:{position:'asc'},select:{id:true,storageUrl:true,altText:true,position:true}},category:{select:{id:true,nameHe:true}},seller:{select:{id:true,businessName:true,store:{select:{name:true}}}},variants:{select:{inventory:{select:{quantity:true,reserved:true}}}}}}),this.db.product.count({where})]);return{data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}};
  }
  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Patch('products/:id/status') async productStatus(@CurrentUser() admin:AuthUser,@Param('id',ParseUUIDPipe) id:string,@Body() dto:AdminProductStatusDto){await this.rateLimit.consume(`admin-sensitive:${admin.sub}`,30,60*1000);const product=await this.db.product.findFirst({where:{id,deletedAt:null}});if(!product)throw new NotFoundException('המוצר לא נמצא');if(product.status===dto.status)throw new ConflictException('סטטוס המוצר כבר עודכן');return this.db.$transaction(async tx=>{const claimed=await tx.product.updateMany({where:{id,status:product.status,deletedAt:null},data:{status:dto.status}});if(claimed.count!==1)throw new ConflictException('סטטוס המוצר השתנה. רעננו ונסו שוב');const updated={id,status:dto.status};await tx.auditLog.create({data:{actorId:admin.sub,action:'ADMIN_PRODUCT_STATUS_CHANGED',entityType:'Product',entityId:id,metadata:{previousStatus:product.status,newStatus:dto.status}}});return updated;});}

  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Get('categories') async categories(@Query('search') search=''){return this.db.category.findMany({where:search?{OR:[{nameHe:{contains:search,mode:'insensitive'}},{slug:{contains:search,mode:'insensitive'}}]}:{},orderBy:[{position:'asc'},{nameHe:'asc'}],select:{id:true,parentId:true,slug:true,nameHe:true,nameAr:true,nameEn:true,active:true,position:true,_count:{select:{products:true,children:true}}}});}
  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Post('categories') createCategory(@Body() dto:AdminCategoryDto){return this.db.category.create({data:dto});}
  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Patch('categories/:id') async updateCategory(@Param('id',ParseUUIDPipe) id:string,@Body() dto:AdminUpdateCategoryDto){if(dto.parentId===id)throw new BadRequestException('קטגוריה אינה יכולה להיות הורה של עצמה');return this.db.category.update({where:{id},data:dto}).catch(()=>{throw new NotFoundException('הקטגוריה לא נמצאה');});}
  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Delete('categories/:id') async deleteCategory(@Param('id',ParseUUIDPipe) id:string){const category=await this.db.category.findUnique({where:{id},select:{_count:{select:{products:true,children:true}}}});if(!category)throw new NotFoundException('הקטגוריה לא נמצאה');if(category._count.products||category._count.children)throw new ConflictException('לא ניתן למחוק קטגוריה עם מוצרים או קטגוריות משנה');await this.db.category.delete({where:{id}});return{message:'הקטגוריה נמחקה'};}

  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Get('orders') async orders(@Query('search') search='',@Query('status') status='',@Query('paymentStatus') paymentStatus='',@Query('page') pageText?:string,@Query('limit') limitText?:string){const {page,limit,skip}=this.page(pageText,limitText);if(status&&!Object.values(OrderStatus).includes(status as OrderStatus))throw new BadRequestException('סטטוס הזמנה לא תקין');if(paymentStatus&&!Object.values(PaymentStatus).includes(paymentStatus as PaymentStatus))throw new BadRequestException('סטטוס תשלום לא תקין');const where={...(search?{orderNumber:{contains:search,mode:'insensitive' as const}}:{}),...(status?{status:status as OrderStatus}:{}),...(paymentStatus?{payment:{is:{status:paymentStatus as PaymentStatus}}}:{})};const [data,total]=await this.db.$transaction([this.db.order.findMany({where,skip,take:limit,orderBy:{createdAt:'desc'},select:{id:true,orderNumber:true,totalAgorot:true,status:true,createdAt:true,user:{select:{email:true,firstName:true,lastName:true}},payment:{select:{status:true}},sellerOrders:{select:{seller:{select:{businessName:true,store:{select:{name:true}}}}}},_count:{select:{sellerOrders:true}}}}),this.db.order.count({where})]);return{data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}};}
  @RequireRoles(Role.ADMIN,Role.SUPER_ADMIN) @Get('orders/:id') async order(@Param('id',ParseUUIDPipe) id:string){const order=await this.db.order.findUnique({where:{id},select:{id:true,orderNumber:true,totalAgorot:true,status:true,shippingAddress:true,createdAt:true,user:{select:{email:true,firstName:true,lastName:true}},payment:{select:{status:true,amountAgorot:true}},sellerOrders:{select:{id:true,subtotalAgorot:true,commissionAgorot:true,netAgorot:true,status:true,seller:{select:{businessName:true,store:{select:{name:true}}}},items:{select:{id:true,productName:true,sku:true,variantName:true,quantity:true,unitPriceAgorot:true,discountAgorot:true,commissionAgorot:true}}}}}});if(!order)throw new NotFoundException('ההזמנה לא נמצאה');return order;}
}

export const dashboardProviders = [SellerService];
