import {BadRequestException,Body,Controller,Delete,ForbiddenException,Injectable,NotFoundException,Param,ParseUUIDPipe,Patch,Post,UploadedFiles,UseInterceptors} from '@nestjs/common';
import {FilesInterceptor} from '@nestjs/platform-express';import {Role,SellerStatus} from '@prisma/client';import {IsBoolean,IsInt,IsOptional,IsString,Max,MaxLength,Min} from 'class-validator';import {randomUUID} from 'crypto';import {mkdir,unlink,writeFile} from 'fs/promises';import {resolve} from 'path';import {AuthUser,CurrentUser,RequireRoles} from './auth';import {PrismaService} from './prisma';
import {detectImage} from './image-validation';
export const MAX_PRODUCT_IMAGES=8,MAX_IMAGE_BYTES=10*1024*1024;type UploadedImage={buffer:Buffer;mimetype:string;size:number;originalname:string};
class ImageUpdateDto{@IsOptional()@IsString()@MaxLength(200)altText?:string;@IsOptional()@IsInt()@Min(0)@Max(MAX_PRODUCT_IMAGES-1)position?:number;@IsOptional()@IsBoolean()isPrimary?:boolean;}
@Injectable()export class ProductMediaService{
 constructor(private readonly db:PrismaService){}private root(){return resolve(process.env.UPLOAD_ROOT??resolve(process.env.INIT_CWD??process.cwd(),'uploads'));}
 private async ownedProduct(userId:string,productId:string){const seller=await this.db.sellerProfile.findUnique({where:{userId},select:{id:true,status:true}});if(!seller||seller.status!==SellerStatus.APPROVED)throw new ForbiddenException('חשבון מוכר מאושר נדרש');const product=await this.db.product.findFirst({where:{id:productId,sellerId:seller.id,deletedAt:null},select:{id:true,nameHe:true,_count:{select:{images:true}}}});if(!product)throw new NotFoundException('המוצר לא נמצא');return product;}
 async add(userId:string,productId:string,files:UploadedImage[]){const product=await this.ownedProduct(userId,productId);if(!files.length)throw new BadRequestException('יש לבחור לפחות תמונה אחת');if(product._count.images+files.length>MAX_PRODUCT_IMAGES)throw new BadRequestException(`ניתן לשמור עד ${MAX_PRODUCT_IMAGES} תמונות למוצר`);const checked=files.map(file=>{if(!file.size||file.size>MAX_IMAGE_BYTES)throw new BadRequestException('גודל התמונה אינו תקין');const detected=detectImage(file.buffer);if(!detected||!['image/jpeg','image/png','image/webp'].includes(file.mimetype)||detected.mime!==file.mimetype)throw new BadRequestException('קובץ התמונה אינו JPG, PNG או WebP תקין');return{file,detected};});const directory=resolve(this.root(),'products',productId);await mkdir(directory,{recursive:true});const existing=await this.db.productImage.count({where:{productId}});const saved:{path:string;url:string;altText:string;position:number}[]=[];try{for(const[index,item]of checked.entries()){const filename=`${randomUUID()}.${item.detected.extension}`,path=resolve(directory,filename);await writeFile(path,item.file.buffer,{flag:'wx'});saved.push({path,url:`/uploads/products/${productId}/${filename}`,altText:product.nameHe,position:existing+index});}return await this.db.$transaction(saved.map(item=>this.db.productImage.create({data:{productId,storageUrl:item.url,altText:item.altText,position:item.position}})));}catch(error){await Promise.allSettled(saved.map(item=>unlink(item.path)));throw error;}}
 async update(userId:string,productId:string,imageId:string,dto:ImageUpdateDto){await this.ownedProduct(userId,productId);const images=await this.db.productImage.findMany({where:{productId},orderBy:[{position:'asc'},{id:'asc'}]}),image=images.find(item=>item.id===imageId);if(!image)throw new NotFoundException('התמונה לא נמצאה');const ordered=images.filter(item=>item.id!==imageId),target=dto.isPrimary?0:Math.min(dto.position??image.position,ordered.length);ordered.splice(target,0,image);await this.db.$transaction(ordered.map((item,position)=>this.db.productImage.update({where:{id:item.id},data:{position,...(item.id===imageId&&dto.altText!==undefined?{altText:dto.altText.trim()||null}:{})}})));return this.db.productImage.findMany({where:{productId},orderBy:{position:'asc'}});}
 async remove(userId:string,productId:string,imageId:string){await this.ownedProduct(userId,productId);const image=await this.db.productImage.findFirst({where:{id:imageId,productId}});if(!image)throw new NotFoundException('התמונה לא נמצאה');const remaining=await this.db.$transaction(async tx=>{await tx.productImage.delete({where:{id:imageId}});const rows=await tx.productImage.findMany({where:{productId},orderBy:[{position:'asc'},{id:'asc'}]});await Promise.all(rows.map((row,position)=>tx.productImage.update({where:{id:row.id},data:{position}})));return rows.map((row,position)=>({...row,position}));});const prefix=`/uploads/products/${productId}/`;if(image.storageUrl.startsWith(prefix)){const filename=image.storageUrl.slice(prefix.length);if(filename&&!filename.includes('/')&&!filename.includes('\\'))await unlink(resolve(this.root(),'products',productId,filename)).catch(error=>console.warn('Product image file cleanup failed',error));}return{message:'התמונה נמחקה',images:remaining};}}
@Controller('seller/products/:productId/images')export class ProductMediaController{constructor(private readonly media:ProductMediaService){}@RequireRoles(Role.SELLER,Role.ADMIN,Role.SUPER_ADMIN)@Post()@UseInterceptors(FilesInterceptor('images',MAX_PRODUCT_IMAGES,{limits:{fileSize:MAX_IMAGE_BYTES,files:MAX_PRODUCT_IMAGES}}))add(@CurrentUser()user:AuthUser,@Param('productId',ParseUUIDPipe)productId:string,@UploadedFiles()files:UploadedImage[]){return this.media.add(user.sub,productId,files??[]);}@RequireRoles(Role.SELLER,Role.ADMIN,Role.SUPER_ADMIN)@Patch(':imageId')update(@CurrentUser()user:AuthUser,@Param('productId',ParseUUIDPipe)productId:string,@Param('imageId',ParseUUIDPipe)imageId:string,@Body()dto:ImageUpdateDto){return this.media.update(user.sub,productId,imageId,dto);}@RequireRoles(Role.SELLER,Role.ADMIN,Role.SUPER_ADMIN)@Delete(':imageId')remove(@CurrentUser()user:AuthUser,@Param('productId',ParseUUIDPipe)productId:string,@Param('imageId',ParseUUIDPipe)imageId:string){return this.media.remove(user.sub,productId,imageId);}}
