"use client";
import Link from "next/link";
import {useState} from "react";
import {mediaUrl} from "../lib/api";
import {Product} from "../lib/types";
import {useCart} from "./cart-context";
import {useWishlist} from "./wishlist-context";
const money=(value:number)=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS"}).format(value/100);
export function ProductCard({product}:{product:Product}){
 const{add}=useCart(),wishlist=useWishlist(),[added,setAdded]=useState(false),[imageFailed,setImageFailed]=useState(false),variant=product.variants[0],currentPrice=variant?.priceAgorot??product.priceAgorot,old=product.compareAtAgorot&&product.compareAtAgorot>currentPrice?product.compareAtAgorot:null,image=mediaUrl(product.images[0]?.storageUrl),discount=old?Math.round((1-currentPrice/old)*100):0,favorite=wishlist.has(product.id);
 function addOne(){if(!variant||product.availableQuantity<1)return;add({productId:product.id,variantId:variant.id,slug:product.slug,name:product.nameHe,priceAgorot:currentPrice,quantity:1,availableQuantity:product.availableQuantity,sellerName:product.seller.store?.name??"מוכר מקומי",image:image&&!imageFailed?image:undefined});setAdded(true);window.setTimeout(()=>setAdded(false),1800)}
 return <article className="productCard"><button type="button" className={`favoriteButton ${favorite?"active":""}`} aria-pressed={favorite} aria-label={favorite?`הסרת ${product.nameHe} מהמועדפים`:`הוספת ${product.nameHe} למועדפים`} onClick={()=>wishlist.toggle(product)}>{favorite?"♥":"♡"}</button><Link className="productCardImage" href={`/product/${product.slug}`}><div className="photo">{discount>0&&<span className="discount">{discount}%−</span>}<div>{image&&!imageFailed?<img src={image} loading="lazy" alt={product.images[0].altText??product.nameHe} onError={()=>setImageFailed(true)}/>:<span className="imageFallback" role="img" aria-label="אין תמונה">ש</span>}</div></div></Link><div className="info"><div className="cardMeta"><span>{product.category.nameHe}</span>{product.supportsFastDelivery&&<b>משלוח מהיר</b>}</div><h3><Link href={`/product/${product.slug}`}>{product.nameHe}</Link></h3><p className="seller">{product.seller.store?<Link href={`/seller/${product.seller.store.slug}`}>{product.seller.store.name}</Link>:<span>מוכר מקומי</span>}<span>★ {product.rating.toFixed(1)}</span></p><p className={product.availableQuantity?"cardStock":"cardStock out"}>{product.availableQuantity?product.availableQuantity<5?`נותרו ${product.availableQuantity}`:"במלאי":"אזל מהמלאי"}</p><div className="price"><span><b>{money(currentPrice)}</b>{old&&<del>{money(old)}</del>}</span><button aria-label={`הוספת ${product.nameHe} לסל`} disabled={!variant||product.availableQuantity<1} onClick={addOne}>{added?"✓":"＋"}</button></div>{added&&<div className="cardNotice" role="status">נוסף לסל</div>}</div></article>
}
