"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {useCart} from "./cart-context";
import {useWishlist} from "./wishlist-context";
import {useLanguage,type Locale} from "./language-context";
function SearchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/></svg>}
function UserIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>}
function CartIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 1.9-1.4L21 8H6"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></svg>}
export function Header(){const router=useRouter(),{count}=useCart(),wishlist=useWishlist(),{locale,setLocale,t}=useLanguage(),[loggedIn,setLoggedIn]=useState(false),[query,setQuery]=useState(""),[menuOpen,setMenuOpen]=useState(false);useEffect(()=>{const sync=()=>setLoggedIn(Boolean(localStorage.getItem("shuk-token")));sync();window.addEventListener("shuk-auth-change",sync);return()=>window.removeEventListener("shuk-auth-change",sync)},[]);function search(event:FormEvent){event.preventDefault();const value=query.trim();router.push(value?`/?search=${encodeURIComponent(value)}#products`:"/#products");setMenuOpen(false)}return <><div className="top"><span>{t("market")}</span><b>{t("live")}</b></div><header className="siteHeader"><Link className="logo" href="/" aria-label="Shuk"><i>ש</i><span>שׁוּק</span><small>SHUK</small></Link><form className="headerSearch" role="search" onSubmit={search}><SearchIcon/><input aria-label={t("search")} value={query} onChange={event=>setQuery(event.target.value)} placeholder={t("searchPlaceholder")}/><button>{t("search")}</button></form><nav className="headerActions" aria-label="Account and cart"><label className="languageSelect"><span className="srOnly">Language</span><select value={locale} onChange={event=>setLocale(event.target.value as Locale)} aria-label="Language"><option value="he">עברית</option><option value="ar">العربية</option><option value="en">English</option></select></label><Link className="favoriteNav" href="/favorites" aria-label={`${t("favorites")}, ${wishlist.items.length}`}><span aria-hidden="true">♡</span><small>{t("favorites")}</small>{wishlist.items.length>0&&<b>{wishlist.items.length}</b>}</Link><Link href={loggedIn?"/account":"/login"} aria-label={loggedIn?t("account"):t("login")}><UserIcon/><span>{loggedIn?t("account"):t("login")}</span></Link><Link className="cart" href="/cart" aria-label={`${t("cart")}, ${count}`}><CartIcon/><span>{t("cart")}</span>{count>0&&<b>{count}</b>}</Link><button type="button" className="menuToggle" aria-expanded={menuOpen} aria-controls="mobile-navigation" aria-label="Menu" onClick={()=>setMenuOpen(value=>!value)}><i/><i/><i/></button></nav></header><nav id="mobile-navigation" className={`mainNav ${menuOpen?"open":""}`} aria-label="Main navigation"><Link href="/#products" onClick={()=>setMenuOpen(false)}>{t("categories")}</Link><Link href="/?sort=newest#products" onClick={()=>setMenuOpen(false)}>{t("new")}</Link><Link href="/?inStock=true#products" onClick={()=>setMenuOpen(false)}>{t("stock")}</Link><Link href="/favorites" onClick={()=>setMenuOpen(false)}>{t("favorites")}</Link><Link href="/become-seller" onClick={()=>setMenuOpen(false)}>{t("sell")}</Link></nav></>}
export function Footer(){const{count}=useCart(),{t}=useLanguage();return <><footer className="siteFooter"><div className="footerBrand"><b><i>ש</i> שׁוּק</b><p>{t("tagline")}</p></div><div><strong>{t("shopping")}</strong><Link href="/#products">{t("allProducts")}</Link><Link href="/#products">{t("categories")}</Link><Link href="/favorites">{t("favorites")}</Link><Link href="/cart">{t("cart")}</Link></div><div><strong>{t("account")}</strong><Link href="/account">{t("profile")}</Link><Link href="/orders">{t("orders")}</Link><Link href="/become-seller">{t("openStore")}</Link></div><small>© 2026 Shuk Marketplace · ₪</small></footer><nav className="bottom" aria-label="Mobile navigation"><Link href="/"><span>⌂</span><small>Home</small></Link><Link href="/#products"><span>◦</span><small>{t("categories")}</small></Link><Link href="/favorites"><span>♡</span><small>{t("favorites")}</small></Link><Link href="/cart"><span>🛒</span><small>{t("cart")} ({count})</small></Link><Link href="/account"><span>♙</span><small>{t("account")}</small></Link></nav></>}
