"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { api } from '../../lib/api';
import { AddressManager } from '../../components/address-manager';
import { Footer,Header } from '../../components/site-shell';
type ShippingAddress={fullName?:string;phone?:string;city?:string;street?:string;houseNumber?:string;apartment?:string;postalCode?:string;notes?:string};
type User={firstName:string;lastName:string;email:string;roles:{role:string}[];seller:{status:string;store:{name:string}|null}|null};
type CustomerOrder={id:string;orderNumber:string;status:string;totalAgorot:number;createdAt:string;shippingAddress?:ShippingAddress;payment:{status:string}|null;sellerOrders:{id:string;seller:{store:{name:string}|null};items:{id:string;productName:string;sku:string;variantName:string|null;quantity:number;unitPriceAgorot:number;discountAgorot:number}[]}[]};
const money=(n:number)=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS'}).format(n/100);
const labels:Record<string,string>={PENDING_PAYMENT:'ממתינה לתשלום',PAID:'שולמה',PROCESSING:'בטיפול',READY_TO_SHIP:'מוכנה למשלוח',SHIPPED:'נשלחה',IN_TRANSIT:'בדרך',DELIVERED:'נמסרה',CANCELLED:'בוטלה',REFUNDED:'הוחזרה'};
function AddressSnapshot({address}:{address?:ShippingAddress}){if(!address?.city||!address.street)return null;return <div className="orderShipping"><b>כתובת משלוח</b><span>{address.fullName}</span><span>{address.street} {address.houseNumber}{address.apartment?`, דירה ${address.apartment}`:''}, {address.city}</span>{address.phone&&<span dir="ltr">{address.phone}</span>}{address.notes&&<small>{address.notes}</small>}</div>}
export default function Account(){
 const[user,setUser]=useState<User|null>(null),[orders,setOrders]=useState<CustomerOrder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState<string|null>(null);const router=useRouter();
 async function load(){const token=localStorage.getItem('shuk-token');if(!token){router.replace('/login');return}setLoading(true);setError('');try{const[profile,myOrders]=await Promise.all([api.authGet<User>('/auth/me',token),api.authGet<CustomerOrder[]>('/orders/my',token)]);setUser(profile);setOrders(myOrders)}catch(cause){setError((cause as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);async function logout(){try{await api.logout()}finally{localStorage.removeItem('shuk-token');window.dispatchEvent(new Event('shuk-auth-change'));router.push('/')}}
 return <main dir="rtl"><Header/><section className="accountPage wrap">{loading?<div className="customerLoading"><span/><p>טוענים את החשבון…</p></div>:error?<div className="customerError"><span>!</span><h2>לא הצלחנו לטעון את החשבון</h2><p>{error}</p><button className="primary" onClick={()=>void load()}>נסו שוב</button></div>:<><div className="accountHeader"><div className="accountAvatar">{user?.firstName?.[0]}{user?.lastName?.[0]}</div><div><label>החשבון שלי</label><h1>שלום {user?.firstName} {user?.lastName}</h1><p>{user?.email}</p></div><div className="accountActions">{user?.roles.some(x=>x.role==='SELLER')&&<Link href="/seller-dashboard">לוח מוכר</Link>}{user?.roles.some(x=>['ADMIN','SUPER_ADMIN'].includes(x.role))&&<Link href="/admin">לוח ניהול</Link>}<button onClick={logout}>התנתקות</button></div></div><SellerStatus user={user}/><AddressManager/><section className="accountOrders"><div className="sellerSectionHead"><div><label>היסטוריה</label><h2>ההזמנות שלי</h2></div><button onClick={()=>void load()}>רענון</button></div>{!orders.length?<div className="customerEmpty"><span>📦</span><h3>עדיין אין הזמנות</h3><p>אחרי הקנייה הראשונה, פרטי ההזמנה יופיעו כאן.</p><Link className="primary" href="/">התחילו לקנות</Link></div>:<div className="customerOrdersList">{orders.map(order=><article key={order.id}><button className="orderSummary" onClick={()=>setOpen(open===order.id?null:order.id)}><div><b dir="ltr">{order.orderNumber}</b><small>{new Intl.DateTimeFormat('he-IL',{dateStyle:'medium'}).format(new Date(order.createdAt))}</small></div><span className="statusBadge">{labels[order.status]??order.status}</span><strong>{money(order.totalAgorot)}</strong><i>{open===order.id?'⌃':'⌄'}</i></button>{open===order.id&&<div className="orderDetails"><div className="orderMeta"><span>מצב הזמנה <b>{labels[order.status]??order.status}</b></span><span>מצב תשלום <b>{order.payment?(labels[order.payment.status]??order.payment.status):'טרם נוצר'}</b></span></div><AddressSnapshot address={order.shippingAddress}/>{order.sellerOrders.map(group=><section key={group.id}><h4>{group.seller.store?.name??'חנות מקומית'}</h4>{group.items.map(item=><p key={item.id}><span>{item.productName}<small>{item.variantName} · SKU {item.sku}</small></span><span>{item.quantity} × {money(item.unitPriceAgorot)}</span><b>{money(item.unitPriceAgorot*item.quantity-item.discountAgorot)}</b></p>)}</section>)}</div>}</article>)}</div>}</section></>}</section><Footer/></main>
}
function SellerStatus({user}:{user:User|null}){const seller=user?.seller;if(!seller)return <section className="sellerAccountCard"><div><h2>רוצים למכור את המוצרים שלכם?</h2><p>פתחו חנות מקומית והצטרפו למוכרים של Shuk.</p></div><Link className="primary" href="/become-seller">פתח חנות</Link></section>;if(['PENDING','UNDER_REVIEW'].includes(seller.status))return <section className="sellerAccountCard"><div><h2>בקשת פתיחת החנות נמצאת בבדיקה</h2><p>נעדכן את החשבון לאחר בדיקת הנהלת Shuk.</p></div></section>;if(seller.status==='APPROVED')return <section className="sellerAccountCard"><div><h2>החנות שלך פעילה</h2><p>{seller.store?.name}</p></div><Link className="primary" href="/seller-dashboard">לוח הבקרה למוכר</Link></section>;return <section className="sellerAccountCard"><div><h2>בקשת פתיחת החנות נדחתה</h2><p>ניתן לעדכן את הפרטים ולהגיש מחדש.</p></div><Link className="primary" href="/become-seller">הגשה מחדש</Link></section>}
